#! /bin/sh 
# reference: MELP book
# https://www.thirtythreeforty.net/posts/2020/03/mastering-embedded-linux-part-4-adding-features/
 
case "$1" in
      start)
           start-stop-daemon -S -n module_load -a /usr/bin/module_load -- faulty
           start-stop-daemon -S -n scull_load -a /usr/bin/scull_load       
           modprobe hello.ko
           start-stop-daemon -S -n module_load -a /usr/bin/aesdchar_load  
           ;;
     stop)    
           start-stop-daemon -S -n module_unload -a /usr/bin/module_unload -- faulty
           start-stop-daemon -S -n scull_unload -a /usr/bin/scull_unload  
           rmmod hello.ko       
           start-stop-daemon -S -n aesdchar_unload -a /usr/bin/aesdchar_unload
           ;;
     *)
           echo "Usage: $0 {start|stop}"
           exit 1
esac

exit 0